cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/',
         views.full_remove, name='full_remove'),
]

epytech1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(
        template_name='accounts/logout.html'), name='logout'),
    path('accounts/register/', accounts_views.register, name='register'),
    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html'), name='password_reset'),
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),

    path('admin/', admin.site.urls),
    path('address/', include('address.urls')),
    path('payment/', include('payment.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
# from .views import CheckoutView
from . import views

app_name = 'orders'

urlpatterns = [
    # path('create/', CheckoutView.as_view(), name='order_create'),
    path('create/', views.order_create, name='order_create'),
    # path('thanks/', views.thanks, name='thanks')
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.shop, name='shop_home'),
    path('category/', views.category, name='category'),
    path('category/<slug:c_slug>/', views.category,
         name='product_list_by_category'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:c_slug>/', views.category_detail, name='category_detail'),
]

cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['-date_added']

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    # def get_discount_price(self):
    #     return self.product.discount_price * self.quantity

    def __str__(self):
        return f'Order {self.product}'

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from shop.models import Product
from . models import Cart, CartItem


# Create your views here.


def _cart_id(request):
    cart = request.session.session_key

    if not cart:
        cart = request.session.create()
    return cart


@login_required
def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart)

        for cart_item in cart_items:

            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    context = {
        'cart_items': cart_items,
        'total': total,
        'counter': counter
    }
    return render(request, 'cart/cart.html', context)


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/templates/cart/cart.html
{% extends 'base.html' %} {% load humanize %} {% block content %}

<div class="container">
  <div class="table-responsive">
    <h3>Cart Summary</h3>
    {% if not cart_items %}
    <div class="container">
      <h2>Your shopping cart is empty</h2>
      <p>
        please click <a href="{% url 'shop:shop_home' %}">here</a> to got to
        shop
      </p>
    </div>
    {% else %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">SKU</th>
          <th scope="col">ITEM</th>
          <th scope="col">UNIT PRICE</th>
          <th scope="col">QTY</th>
          <th scope="col">SUBTOTAL</th>
        </tr>
      </thead>
      <tbody>
        {% for cart_item in cart_items %}
        <tr>
          <th scope="row">1</th>
          <td>{{ cart_item.product.id }}</td>
          <td>{{ cart_item.product.name }}</td>
          <td>&#8358;{{ cart_item.product.price | intcomma }}</td>
          <td>
            {% if cart_item.quantity < cart_item.product.stock %}
            <a
              class="mr-2"
              href="{% url 'cart:add_cart' cart_item.product.id %}"
              ><i class="fas fa-plus"></i
            ></a>
            {{ cart_item.quantity }}
            <a
              class="ml-2"
              href="{% url 'cart:cart_remove' cart_item.product.id %}"
              ><i class="fas fa-minus"></i
            ></a>
            <a
              class="ml-2"
              href="{% url 'cart:full_remove' cart_item.product.id %}"
              ><i style="color:red" class="far fa-trash-alt"></i
            ></a>

            {% else %}
            <a href="{% url 'cart:cart_remove' cart_item.product.id %}"
              ><i class="fas fa-minus"></i
            ></a>
            <a href="{% url 'cart:full_remove' cart_item.product.id %}"
              ><i class="far fa-trash-alt" style="color:red"></i
            ></a>
            {% endif %}
          </td>
          <td>&#8358;{{ cart_item.sub_total | intcomma }}</td>

          {% endfor %}
        </tr>
        <tr>
          <td colspan="5">Grand Total</td>
          <td>&#8358;{{ total | intcomma }}</td>
        </tr>
        <tr>
          <td colspan="6">
            <a
              class="btn btn-danger float-right"
              href="{% url 'shop:shop_home' %}"
              >Continue Shopping</a
            >
            <a
              class="btn btn-primary float-right mr-2"
              href="{% url 'orders:order_create' %}"
              >Checkout</a
            >
          </td>
        </tr>
      </tbody>
    </table>
    {% endif %}
  </div>
</div>

{% endblock %}